services:
  backend:
    build: ./backend
    ports:
      - "5000:5000"
    volumes:
      - ./backend:/app
      - /app/node_modules
    restart: always

  frontend:
    build: ./frontend
    ports:
      - "3000:5173"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    restart: always

  fastapi_backend:
    build: ./fastapi_backend
    ports:
      - "8000:8000"
    volumes:
      - ./fastapi_backend:/app
    restart: always
